### ISSUE TITLE
macOS 版 adafruit-nrfutil がロケールのエラーで使用できない

### ISSUE THREAD

**Issue by osaboh** [SWITCHSCIENCE/Arduino_Board_Package#1]
macOS 版 adafruit-nrfutil がロケールのエラーで使用できませんでした。
以下を参考に adafruit-nrfutil を入れ替えることで書き込みに成功しました。パッケージ更新の検討をお願いします。

[Upgrading Issue: RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment](https://forum.arduino.cc/t/upgrading-issue-runtimeerror-click-will-abort-further-execution-because-python-3-was-configured-to-use-ascii-as-encoding-for-the-environment/1078618)

adafruit-nrfutil をこれに変更
https://github.com/adafruit/Adafruit_nRF52_nrfutil/releases/tag/0.5.3.post16

ボード名: Switch Science BLE-SS dev board Multi Sensor
Arduino IDE: v2.2.1
macOS: Sonoma 14.1.2 (ARM 版)
エラーメッセージ:
> /Users/osanai/Library/Arduino15/packages/switchscience/hardware/nrf52/0.1.9/tools/adafruit-nrfutil/macos/adafruit-nrfutil dfu genpkg --dev-type 0x0052 --sd-req 0x00B6 --application /private/var/folders/jw/5qprjyc17xgg4zkdvgp13tg40000gn/T/arduino/sketches/D3EA87C213D861DCCCD0A2C0D872935F/adv_env.ino.hex /private/var/folders/jw/5qprjyc17xgg4zkdvgp13tg40000gn/T/arduino/sketches/D3EA87C213D861DCCCD0A2C0D872935F/adv_env.ino.zip
> [59063] Failed to execute script __main__
> Traceback (most recent call last):
>   File "nordicsemi/__main__.py", line 315, in <module>
>   File "click/core.py", line 722, in __call__
>   File "click/core.py", line 676, in main
>   File "click/_unicodefun.py", line 118, in _verify_python3_env
> RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment.  Consult http://click.pocoo.org/python3/for mitigation steps.
> 
> This system lists a couple of UTF-8 supporting locales that
> you can pick from.  The following suitable locales where
> discovered: af_ZA.UTF-8, am_ET.UTF-8, be_BY.UTF-8, bg_BG.UTF-8, ca_ES.UTF-8, cs_CZ.UTF-8, da_DK.UTF-8, de_AT.UTF-8, de_CH.UTF-8, de_DE.UTF-8, el_GR.UTF-8, en_AU.UTF-8, en_CA.UTF-8, en_GB.UTF-8, en_IE.UTF-8, en_NZ.UTF-8, en_US.UTF-8, es_ES.UTF-8, et_EE.UTF-8, eu_ES.UTF-8, fi_FI.UTF-8, fr_BE.UTF-8, fr_CA.UTF-8, fr_CH.UTF-8, fr_FR.UTF-8, he_IL.UTF-8, hr_HR.UTF-8, hu_HU.UTF-8, hy_AM.UTF-8, is_IS.UTF-8, it_CH.UTF-8, it_IT.UTF-8, ja_JP.UTF-8, kk_KZ.UTF-8, ko_KR.UTF-8, lt_LT.UTF-8, nl_BE.UTF-8, nl_NL.UTF-8, no_NO.UTF-8, pl_PL.UTF-8, pt_BR.UTF-8, pt_PT.UTF-8, ro_RO.UTF-8, ru_RU.UTF-8, sk_SK.UTF-8, sl_SI.UTF-8, sr_YU.UTF-8, sv_SE.UTF-8, tr_TR.UTF-8, uk_UA.UTF-8, zh_CN.UTF-8, zh_HK.UTF-8, zh_TW.UTF-8
> 
> 次のフォルダのライブラリAdafruit Bluefruit nRF52 Librariesバージョン0.21.0を使用中：/Users/osanai/Library/Arduino15/packages/adafruit/hardware/nrf52/1.5.0/libraries/Bluefruit52Lib 
> 次のフォルダのライブラリAdafruit nRFCryptoバージョン0.0.7を使用中：/Users/osanai/Library/Arduino15/packages/adafruit/hardware/nrf52/1.5.0/libraries/Adafruit_nRFCrypto 
> 次のフォルダのライブラリAdafruit TinyUSB Libraryバージョン2.0.1を使用中：/Users/osanai/Library/Arduino15/packages/adafruit/hardware/nrf52/1.5.0/libraries/Adafruit_TinyUSB_Arduino 
> 次のフォルダのライブラリWireバージョン1.0を使用中：/Users/osanai/Library/Arduino15/packages/adafruit/hardware/nrf52/1.5.0/libraries/Wire 
> 次のフォルダのライブラリAdafruit Little File System Librariesバージョン0.11.0を使用中：/Users/osanai/Library/Arduino15/packages/adafruit/hardware/nrf52/1.5.0/libraries/Adafruit_LittleFS 
> 次のフォルダのライブラリAdafruit Internal File System on Bluefruit nRF52バージョン0.11.0を使用中：/Users/osanai/Library/Arduino15/packages/adafruit/hardware/nrf52/1.5.0/libraries/InternalFileSytem 
> exit status 255
> 
> Compilation error: exit status 255

**Comment by arms22** [comment]
ご連絡ありがとうございます。対応が遅くなってすみません。
0.1.10で対応しました。
